add:button component delete: Buttonfile SecondButtonfile
araisakie/React_User-Management pull request #17
Opened 2021-12-18 09:40 UTC by araisakie

ボタンの共通化
・キャンセル、保存ボタンを一つのjsxでまとめた
・使用しなくなった不要なファイルを削除

2021-12-20 15:01 UTC, shogo4131 requested changes
二つコメントした！
あと削除ボタンも共通化したとこ修正しておいて！

2021-12-20 15:01 UTC, shogo4131 commented on src/pages/SignUp.jsx
> +          />
childrenは
`<Button>削除</Button>`
みたいな感じでラップしたら渡せるから修正してみて！

2021-12-20 15:01 UTC, shogo4131 commented on src/pages/SignUp.jsx
> +          <Button styleType={"save"} onClick={onClickSave} child={"保存"} />
`styleType={"save"}`は`styleType="save"`で書けるから他のとこも修正お願い！

2021-12-26 06:05 UTC, shogo4131 approved these changes
LGTM👍

2021-12-26 06:10 UTC, shogo4131 requested changes
修正追加お願い！

2021-12-26 06:10 UTC, shogo4131 commented on src/component/atoms/button/BaseButton.jsx
> +export default Button;
34行目でexport してるから40行目は消して！

2022-01-07 09:45 UTC, merged

2022-01-07 09:47 UTC, araisakie commented on src/pages/SignUp.jsx
> +          <Button styleType={"save"} onClick={onClickSave} child={"保存"} />
テスト